name: Build
on:
  push:
    branches:
      - develop
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Docker build and deploy to Render
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: lab1-app:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to Render
        if: github.ref == 'refs/heads/develop'
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
          github_deployment: true

      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: postman/[inst] Lab1.postman_collection.json
          environment: postman/[inst][render] Lab1.postman_environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'
